### ISSUE TITLE
Issue by @MohamedCK

### ISSUE THREAD

**Issue by CakeInTech** [PraisesPJMT/Bug-exercise#1]
## Formvalidtion.js Bugs

**Hello there 👋** 

-  In your [code](https://github.com/PraisesPJMT/Bug-exercise/blob/main/javascript/formvalidation.js#L1-L4 ) You need to use (.) for the classes and not the ($) sign otherwise you won't be able to assign the variable to the element.

**Comment by PraisesPJMT** [comment]
Thanks! I identified the bug and fixed it as recommended!

Happy coding!! :+1:
